version: '3'

volumes:
  db:

services:
  livefeedback:
    image: 0xb1b1/livefeedback:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:14
    # ports:
    #   - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "db:/var/lib/postgresql/data"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 8087:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: test@test.com
  #     PGADMIN_DEFAULT_PASSWORD: itam666
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./temp/pgadmin:/var/lib/pgadmin
